include: package:very_good_analysis/analysis_options.7.0.0.yaml
analyzer:
  errors:
    avoid_print: ignore
    document_ignores: ignore
    inference_failure_on_function_invocation: ignore
    lines_longer_than_80_chars: ignore
    prefer_const_constructors: ignore
